application: darkreactionsproject
version: 0-08
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

admin_console:
  pages:
  - name: Django Admin
    url: /admin/

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /favicon.ico
  static_dir: static/favicon.ico
  
###For some reason, GAE needs the "/*" but Django hates it.
- url: /static
  static_dir: static
  
#- url: /static/*
  #static_dir: static
  
- url: /.*
  script: djangoappengine.main.application
